export const FETCH_CHALLENGES = 'FETCH_CHALLENGES';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const SELECT_CHALLENGE = 'SELECT_CHALLENGE';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_SESSION = 'CREATE_SESSION';
