export const FETCH_CHALLENGES = 'FETCH_CHALLENGES';
export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const FETCH_REPOS = 'FETCH_REPOS';
export const CREATE_SESSION = 'CREATE_SESSION';
export const DESTROY_SESSION = 'DESTROY_SESSION';
